# Generated by Django 4.1.1 on 2022-09-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(default='client', on_delete=django.db.models.deletion.CASCADE, to='authcore.role', to_field='code'),
        ),
    ]
