# Generated by Django 4.1.1 on 2022-09-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0003_alter_role_code_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
            ],
        ),
    ]
