# Generated by Django 4.1.1 on 2022-09-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='client', on_delete=django.db.models.deletion.CASCADE, to='authcore.role', to_field='code'),
        ),
    ]
