# Generated by Django 3.2.15 on 2022-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_glass_glasstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glass',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
