# Generated by Django 3.2.15 on 2022-09-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220916_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glass',
            options={'verbose_name_plural': 'Glass'},
        ),
    ]
