# Generated by Django 3.2.15 on 2022-09-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_glass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='car_model',
            field=models.ManyToManyField(related_name='car_models', to='catalog.CarModel'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='type',
            field=models.ManyToManyField(help_text='Введите тип стекла', related_name='types', to='catalog.GlassType'),
        ),
    ]
