# Generated by Django 3.2.15 on 2022-09-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
